cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7114695
  brandStrength: 0.7526882
  lightness: 0.5788531
  brandColors:
    - '#3A2921'
    - '#FFFFFF'
    - '#5B4B43'
    - '#C5BDB4'
    - '#875D27'
  rhythmicContrast: 0.7240143
typography_spectrum: 0.109319
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Zonascope
