name: Zonascope
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7de0c88-749d-489b-8569-4be928ae0b76.png
layout_spectrum: 0.10592
typography_spectrum: 0.46053
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64338413-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7f86a0'
    - '#263a53'
    - '#f5f3f6'
    - '#846340'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - type: external
    url: 'http://apple.co/2jkSrTc'
    label: Get the App
  - type: contact
    url: 'mailto:info@zonascope.com'
    label: Contact me
content: []
title: Zonascope Brain Tracker App
description: Track your optimal brain productivity times
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1946c80e-65e0-45d7-8b64-12c5f8262076.png
author:
  name: ''
